Spawns:
    amount: 3
    world: Frozen
    1:
        x: 0.0
        y: 0.0
        z: 0.0
    2:
        x: 0.0
        y: 0.0
        z: 0.0
    3:
        x: 0.0
        y: 0.0
        z: 0.0
Lobby:
    world: Lobby
    x: 0.0
    y: 0.0
    z: 0.0
        